version: '3.8'

services:
  users-service:
    build: ./users-service
    container_name: users-service
    ports:
      - "8001:8000"
    networks:
      - backend
    extra_hosts:
    - "host.docker.internal:host-gateway"

  stocks-service:
    build: ./stocks-service
    container_name: stocks-service
    ports:
      - "8002:8000"
    networks:
      - backend
    extra_hosts:
    - "host.docker.internal:host-gateway"

  orders-service:
    build: ./orders-service
    container_name: orders-service
    ports:
      - "8003:8000"
    networks:
      - backend
    extra_hosts:
    - "host.docker.internal:host-gateway"

  frontend-service:
    build: ./frontend-service
    container_name: frontend-service
    ports:
      - "8000:8000"
    networks:
      - backend
    extra_hosts:
    - "host.docker.internal:host-gateway"

networks:
  backend:
    driver: bridge
